### PR TITLE
Feature/basinmask 1x1

### PR DESCRIPTION
**Pull request by jkrasting**
Function to dynamically generate a 1x1 basin mask:

image

### CODE REVIEW

**Comment by raphaeldussin** [comment]
I'm happy with the code but I think we need to rethink the directory structure and consolidate between 

data
notebooks
omlabs/resources

which each contain either obs data or related notebooks

Also, where does the land_mask file come from? wouldn't it be cleaner to have a notebook to generate it
from scratch?

**Comment by jkrasting** [comment]
The land_mask file was downloaded from the NODC website.  File in this repo is an exact copy.

https://www.nodc.noaa.gov/OC5/woa13/masks13.html

**Comment by raphaeldussin** [comment]
I think we should avoid adding data files as much as possible to avoid bloating the repo (this one is 1.2MB)
and put a link/reference

**Comment by jkrasting** [comment]
Closed.  Commits are in #35.

**Pull request closed without merging**
