### PR TITLE
Updates to generic image handler for multiple figs

### PR DESCRIPTION
**Pull request by jkrasting**
- option to pass list of filenames rather than
  hardcode counter in filename

### CODE REVIEW

**Comment by raphaeldussin** [comment]
I approve the PR when it passes the testing

**Comment by jkrasting** [comment]
Yeah, looks like an issue with the ESMF build.  Just out of curiosity - is xESMF working on a simpler install?

**Comment by raphaeldussin** [comment]
yes, we could install it with conda like I've done here:

https://github.com/raphaeldussin/OM5x5_tideamp/blob/master/ci/environment-py38esmf800.yml

**Comment by raphaeldussin** [comment]
this needs to be rebased to my master

**Comment by jkrasting** [comment]
Looks fine to me.  What is the issue?

**Pull request merged**
