### PR TITLE
Initial set of Makefile-based testing updates

### PR DESCRIPTION
**Pull request by jkrasting**
**Updates so far:**
- Split reference data in two tar files, one for
  obs and another for model data
- Added both tar files to .gitignore
- Updated default timeseries discovery to
  "ts/monthly" to accomodate test data. This will
  improve performance regardless

**Still to do:**
- Fix sea ice plots (Needs `mask` field in ice_1x1deg.static.nc file)
- Develop tests/datasets for 1/4 and 1/2-degree models

### CODE REVIEW

**Comment by jkrasting** [comment]
@raphaeldussin - I have a similar test dataset for the 0.25-deg model.  Do you think a second Makefile is the way to go?

**Comment by raphaeldussin** [comment]
I think multiple Makefiles is fine, we can run them in the ci with `make -f Makefile.OM4p25`

**Comment by raphaeldussin** [comment]
I don't understand why this PR removes intake catalogs and makes changes to image handler

**Comment by jkrasting** [comment]
> I don't understand why this PR removes intake catalogs and makes changes to image handler

The intake catalogs still exist for the observational data but were removed for the model configurations.  You have managed to convince me that we should be using *.static.nc files, especially those that pair with a particular experiment.  We should be encouraging the use the `-s` flag every time when calling a diagnostic.

The fix to the image handler address a bug where om4labs fails if the output image directory specified by the `-o` flag does not exist.

**Comment by raphaeldussin** [comment]
we should still keep the catalogs for retro-compatibility. Now that we have them, we're stuck with them :)

**Pull request merged**
